server:
  port: 9080
  servlet:
    context-path: /
spring:
  datasource:
    #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/yydb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
#mybatis-plush配置
mybatis-plus:
  type-aliases-package: com.yy.pojo
  mapper-locations: classpath:/mybatis/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level: 
    com.yy.mapper: debug
    
    #SpringBoot整合dubbo   
dubbo:
  scan:
    basePackages: com.yy    #扫描dubbo的注解
  application:
    name: provider-user-manager     #定义服务名称
  registry:                 #dubbo链接zookeeper
    address: zookeeper://192.168.64.128:2181?backup=192.168.64.128:2182,192.168.64.128:2183
  protocol:                 #协议
    name: dubbo             #dubbo协议
    port: 20881             #具体服务端口号 不能重复
